name: GitHub CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test_Android:
    runs-on: macos-26
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
        
    - name: SDL Android Tests (ARM64)
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 36               
        target: google_apis          
        arch: arm64-v8a                        
        cores: 1
        ram-size: 6144
        heap-size: 512
        script: ./android/gradlew -p ./android :sdl_android:connectedCheck
        emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -no-metrics
        
    - name: Hello Sdl Android Tests
      run: ./android/gradlew -p ./android/hello_sdl_android test

    - name: Codecov	
      uses: codecov/codecov-action@v1.0.13
      with:
        yml: ./codecov.yml

  test_Java:
    runs-on: macos-13
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - name: Sdl JavaSE Tests
      run: ./javaSE/gradlew -p ./javaSE/javaSE test
      
    - name: Hello Sdl JavaSE Tests
      run: ./javaSE/gradlew -p ./javaSE/hello_sdl_java test
    
    - name: Sdl JavaEE Tests
      run: ./javaEE/gradlew -p ./javaEE/javaEE test

