name: GitHub CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test_Android:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: SDL Android Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 36
        target: default 
        arch: x86_64
        profile: pixel_7
        no-audio: true 
        ram-size: 2048M 
        disk-size: 4096M 
        disable-animations: true
        emulator-boot-timeout: 1200
        script: ./android/gradlew -p ./android :sdl_android:connectedDebugAndroidTest

    - name: Hello Sdl Android Tests
      run: ./android/gradlew -p ./android/hello_sdl_android test

    - name: Codecov	
      uses: codecov/codecov-action@v1.0.13
      with:
        yml: ./codecov.yml

  test_Java:
    runs-on: macos-13
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - name: Sdl JavaSE Tests
      run: ./javaSE/gradlew -p ./javaSE/javaSE test
      
    - name: Hello Sdl JavaSE Tests
      run: ./javaSE/gradlew -p ./javaSE/hello_sdl_java test
    
    - name: Sdl JavaEE Tests
      run: ./javaEE/gradlew -p ./javaEE/javaEE test

